### PR TITLE
Update Linux/MacOS bindings to MySQL client 8.0

### PR DESCRIPTION
**Pull request by alfonso-eusebio**
This is the PR discussed in diesel's issue diesel-rs/diesel#2373.
It includes the **update of the bindings to support MySQL client library 8.0** for the common Linux/MacOS bindings_macos.rs file.

### Tests:

- This crate - **passed** on Linux
- Diesel's crate - test **passed** for the master branch against libmysqlclient20 (MySQL 5.7) and libmysqlclient21 (MySQL 8.0); both on Linux (Ubuntu 18.04 and 20.04, respectively).

### Limitations:

- No tests run on MacOS
- This PR does **not** include an update for the Windows bindings (bindings_windows.rs)

### CODE REVIEW

**Comment by weiznich** [comment]
@sgrif Any chance to get you to have a look a this? I've unfortunately no rights in this repo (and pq-sys as well). It probably makes sense to transfer them both to the diesel organization?

**Comment by weiznich** [comment]
@yerke Not for the next for weeks/months as I just don't have the capacity to review and untested +3600 line PR.

**Comment by yerke** [comment]
@weiznich Perfectly understandable. Thanks for the quick response!

**Comment by weiznich** [comment]
Closed as duplicate of #37

**Pull request closed without merging**
