### PR TITLE
Add static option

### PR DESCRIPTION
**Pull request by Diggsey**

### CODE REVIEW

**Comment by Diggsey** [comment]
Fixes #17

**Comment by Diggsey** [comment]
@sgrif bump

**Comment by VentGrey** [comment]
another bump?

**Comment by VentGrey** [comment]
As in "what does this PR do"? :thinking:

**Comment by weiznich** [comment]
> As in "what does this PR do"?

As in something user can find and read. So mostly adding the relevant environment variables at least to the crates readme.

**Comment by VentGrey** [comment]
I don't know if the PR author can read these messages 😅 if no response is given I can open another PR using their changes + documentation.

**Comment by weiznich** [comment]
Closed as this was implemented as part of #40

**Pull request closed without merging**
